import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  antigravityInstructionPath,
  claudeInstructionPath,
  codexInstructionPath,
  pluginSkillRelPath,
  questSkillContent,
  questSkillDoc,
} from "../src/application/agents/agent-instructions.ts";
import { findQuestGuide } from "../src/application/agents/guides.ts";

/**
 * QCLI-372 (opum-doc ADR "Distribute lore and quest agent skills through the
 * plugin marketplace", gap 3). The opum-quest plugin's skill was kept by hand
 * beside the generated `questSkillContent`, with nothing relating the two, and
 * it had already drifted: it named two instruction files where the CLI names
 * three. Both copies are now generated by `questSkillDoc`, differing only in
 * the sentence that says where the skill came from, and these tests hold the
 * committed plugin copy to that. Modelled on lore-cli's
 * test/plugin-skill.test.ts (LCLI-573).
 */
describe("the plugin skill stays in lockstep with the generated skill (QCLI-372)", () => {
  const committed = readFileSync(
    join(import.meta.dir, "..", pluginSkillRelPath),
    "utf8",
  );

  test("the committed plugin skill is exactly the generated plugin variant", () => {
    // On failure: `bun run scripts/plugin-skill.mjs --write`.
    expect(committed).toBe(questSkillDoc("plugin"));
  });

  test("the repo skill quest agents writes is the generated repo variant", () => {
    expect(questSkillContent).toBe(questSkillDoc("repo"));
  });

  test("the two variants differ only in their provenance sentence", () => {
    const pluginOnly = "installed from the `opum-quest` Claude Code";
    expect(questSkillDoc("plugin")).toContain(pluginOnly);
    expect(questSkillDoc("repo")).not.toContain(pluginOnly);
    const withoutProvenance = (doc: string) =>
      doc.replace(/^This skill is a pointer[\s\S]*?installed:$/mu, "");
    expect(withoutProvenance(questSkillDoc("plugin"))).toBe(
      withoutProvenance(questSkillDoc("repo")),
    );
  });

  for (const source of ["repo", "plugin"] as const) {
    test(`the ${source} skill names only instruction guides the CLI serves`, () => {
      const doc = questSkillDoc(source);
      const cited = [...doc.matchAll(/`quest instructions ([a-z][a-z-]*)`/gu)];
      expect(cited.length).toBeGreaterThan(0);
      for (const [, name] of cited) expect(findQuestGuide(name)).toBeDefined();
    });

    test(`the ${source} skill names every instruction file the CLI can target`, () => {
      for (const file of [
        codexInstructionPath,
        claudeInstructionPath,
        antigravityInstructionPath,
      ]) {
        expect(questSkillDoc(source)).toContain(file);
      }
    });
  }
});
