import type { TrackerManifest, TrackerTask } from "./index.ts";

export const trackerConformanceFixtureVersion = 1 as const;

export const trackerManifestFixture: TrackerManifest = {
  commands: [
    {
      name: "task status-flow",
      schemaVersion: 1,
      kind: "task.status-flow",
      mutates: false,
      fields: ["statuses", "terminalStatuses"],
    },
    {
      name: "task list",
      schemaVersion: 1,
      kind: "task.list",
      mutates: false,
      filters: [
        "assignee",
        "exclude-status",
        "label",
        "limit",
        "milestone",
        "parent",
        "priority",
        "ready",
        "search",
        "sort",
        "status",
        "type",
        "unassigned",
      ],
      fields: [
        "assignees",
        "createdAt",
        "id",
        "labels",
        "ordinal",
        "priority",
        "status",
        "summary",
        "title",
        "type",
        "updatedAt",
      ],
    },
    {
      name: "task view",
      schemaVersion: 1,
      kind: "task.view",
      mutates: false,
      fields: [
        "acceptanceCriteria",
        "aliases",
        "assignees",
        "comments",
        "createdAt",
        "definitionOfDone",
        "dependencies",
        "description",
        "documentation",
        "finalSummary",
        "id",
        "implementationNotes",
        "labels",
        "milestoneId",
        "modifiedFiles",
        "ordinal",
        "parentId",
        "plan",
        "priority",
        "references",
        "status",
        "summary",
        "title",
        "type",
        "updatedAt",
      ],
    },
    {
      name: "search",
      schemaVersion: 1,
      kind: "task.search",
      mutates: false,
      filters: ["query"],
      fields: [
        "assignees",
        "createdAt",
        "id",
        "labels",
        "ordinal",
        "priority",
        "status",
        "summary",
        "title",
        "type",
        "updatedAt",
      ],
    },
    {
      name: "task create",
      schemaVersion: 1,
      kind: "task.created",
      mutates: true,
      fields: [
        "acceptanceCriteria",
        "aliases",
        "assignees",
        "comments",
        "definitionOfDone",
        "description",
        "documentation",
        "finalSummary",
        "implementationNotes",
        "labels",
        "milestoneId",
        "modifiedFiles",
        "ordinal",
        "parentId",
        "plan",
        "priority",
        "references",
        "summary",
        "title",
        "type",
      ],
    },
    {
      name: "task edit",
      schemaVersion: 1,
      kind: "task.updated",
      mutates: true,
      fields: [
        "acceptanceCriteria",
        "addAssignees",
        "addComments",
        "addDependencies",
        "addLabels",
        "addModifiedFiles",
        "addNotes",
        "addPlan",
        "addReferences",
        "checkAcceptanceCriteria",
        "checkDefinitionOfDone",
        "clearAcceptanceCriteria",
        "clearDefinitionOfDone",
        "clearMilestone",
        "clearParent",
        "comments",
        "definitionOfDone",
        "description",
        "documentation",
        "implementationNotes",
        "labels",
        "milestoneId",
        "ordinal",
        "parentId",
        "plan",
        "priority",
        "removeAcceptanceCriteria",
        "removeAssignees",
        "removeComments",
        "removeDefinitionOfDone",
        "removeDependencies",
        "removeLabels",
        "removeModifiedFiles",
        "removeNotes",
        "removePlan",
        "removeReferences",
        "status",
        "summary",
        "title",
        "type",
        "uncheckAcceptanceCriteria",
        "uncheckDefinitionOfDone",
      ],
    },
  ],
};

export const trackerTaskFixture: TrackerTask = {
  id: "T-1",
  title: "Conformance task",
  status: "To Do",
  labels: ["doc:story"],
  summary: "Public tracker record",
  description: "A public conformance fixture.",
  acceptanceCriteria: [{ index: 0, text: "round-trip", checked: false }],
  definitionOfDone: [{ index: 0, text: "reviewed", checked: true }],
  plan: [],
  implementationNotes: [],
  comments: [],
  documentation: ["docs/stories/example.md"],
  dependencies: [],
  assignees: ["person-1"],
  ordinal: 1,
  createdAt: "2026-08-21T00:00:00Z",
  updatedAt: "2026-08-21T00:00:00Z",
  references: ["QCLI-97.11"],
  modifiedFiles: ["src/domain/tasks/tasks.ts"],
  finalSummary: "Conformance complete.",
  milestoneId: "M-1",
  priority: "high",
  type: "feature",
};

/** Public records only; consumers need no Quest implementation files to run these cases. */
export const trackerConformanceFixtures = {
  version: trackerConformanceFixtureVersion,
  versionOutput: "0.1.0\n",
  manifest: {
    schemaVersion: 1,
    kind: "manifest.registry",
    data: trackerManifestFixture,
  },
  statusFlow: {
    schemaVersion: 1,
    kind: "task.status-flow",
    data: {
      statuses: ["To Do", "In Progress", "Done"],
      terminalStatuses: ["Done"],
    },
  },
  list: { schemaVersion: 1, kind: "task.list", data: [trackerTaskFixture] },
  view: { schemaVersion: 1, kind: "task.view", data: trackerTaskFixture },
  search: { schemaVersion: 1, kind: "task.search", data: [trackerTaskFixture] },
  created: { schemaVersion: 1, kind: "task.created", data: trackerTaskFixture },
  updated: { schemaVersion: 1, kind: "task.updated", data: trackerTaskFixture },
  outcomes: [
    "usage",
    "not_found",
    "denied",
    "conflict",
    "validation",
    "drift",
    "uncaught",
  ] as const,
} as const;
